version: '3.8'

services:

  redis:
    image: "redis:latest"    
    container_name: docker-redis
    ports:
        - '6379:6379'    
    restart: unless-stopped
    networks:
      - app-net    

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: docker-sql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=MyPass@word
    ports:
      - "4000:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-net
      

  api:
    image: conc-api-service
    container_name: conc-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production    
    restart: unless-stopped    
    build:      
      dockerfile: ./Concs.Api/Dockerfile      
    ports:
      - "4002:80"
    depends_on: 
      - sql
      - redis
    networks:
      - app-net
  
  app:
    image: conc-app-service
    container_name: conc-web
    environment:
      ASPNETCORE_ENVIRONMENT: Production    
    restart: unless-stopped    
    build:      
      dockerfile: ./Concs.Web/Dockerfile      
    ports:
      - "4003:80"
    depends_on: 
      - api
    networks:
      - app-net  

volumes:
  sql-data:

networks:
  app-net:
    driver: bridge

  