// <auto-generated />
using System;
using Concs.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concs.Dados.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Concs.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CPF = "12345678901",
                            Nome = "Maria Silva",
                            Telefone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CPF = "98765432109",
                            Nome = "João Santos",
                            Telefone = "(21) 5555-1234"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CPF = "78912345602",
                            Nome = "Carlos Oliveira",
                            Telefone = "(31) 98765-9876"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CPF = "65432198703",
                            Nome = "Ana Rodrigues",
                            Telefone = "(41) 5555-5678"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CPF = "45678912304",
                            Nome = "Fernanda Lima",
                            Telefone = "(51) 98765-4321"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CPF = "32165498705",
                            Nome = "Rafael Souza",
                            Telefone = "(21) 5555-6789"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CPF = "65498732106",
                            Nome = "Lúcia Santos",
                            Telefone = "(31) 98765-1234"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CPF = "98732165407",
                            Nome = "Pedro Alves",
                            Telefone = "(41) 5555-2345"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CPF = "78945612308",
                            Nome = "Mariana Oliveira",
                            Telefone = "(51) 98765-5678"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CPF = "98732165409",
                            Nome = "Lucas Rodrigues",
                            Telefone = "(21) 5555-7890"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CPF = "65478932110",
                            Nome = "Isabela Almeida",
                            Telefone = "(31) 98765-2345"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CPF = "98765432111",
                            Nome = "Gustavo Lima",
                            Telefone = "(41) 5555-3456"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CPF = "78912345612",
                            Nome = "Larissa Costa",
                            Telefone = "(51) 98765-6789"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CPF = "98765432113",
                            Nome = "Ricardo Santos",
                            Telefone = "(21) 5555-8901"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CPF = "65498732114",
                            Nome = "Camila Alves",
                            Telefone = "(31) 98765-3456"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CPF = "98732165415",
                            Nome = "Fábio Lima",
                            Telefone = "(41) 5555-4567"
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Concessionaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConcessionariaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CapacidadeMaximaVeiculos")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Concessionarias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CEP = "01234567",
                            CapacidadeMaximaVeiculos = 150,
                            Cidade = "São Paulo",
                            Email = "contato@concessionariadovale.com.br",
                            Endereco = "Rua das Flores, 123",
                            Estado = "São Paulo",
                            Nome = "Concessionária do Vale",
                            Telefone = "(11) 9876-5432"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CEP = "09876543",
                            CapacidadeMaximaVeiculos = 200,
                            Cidade = "Santo André",
                            Email = "vendas@autocenterabc.com",
                            Endereco = "Av. das Palmeiras, 456",
                            Estado = "São Paulo",
                            Nome = "Auto Center ABC",
                            Telefone = "(11) 5555-1234"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CEP = "20000123",
                            CapacidadeMaximaVeiculos = 180,
                            Cidade = "Rio de Janeiro",
                            Email = "vendas@autoshopzeta.com",
                            Endereco = "Rua dos Carros, 789",
                            Estado = "Rio de Janeiro",
                            Nome = "Auto Shop Zeta",
                            Telefone = "(21) 9876-5432"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CEP = "30000456",
                            CapacidadeMaximaVeiculos = 220,
                            Cidade = "Belo Horizonte",
                            Email = "contato@megamotors.com.br",
                            Endereco = "Av. das Rodovias, 567",
                            Estado = "Minas Gerais",
                            Nome = "Mega Motors",
                            Telefone = "(31) 5555-1234"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CEP = "80000789",
                            CapacidadeMaximaVeiculos = 190,
                            Cidade = "Curitiba",
                            Email = "vendas@carrosexpress.com",
                            Endereco = "Av. das Velocidades, 789",
                            Estado = "Paraná",
                            Nome = "Carros Express",
                            Telefone = "(41) 5555-6789"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CEP = "90000123",
                            CapacidadeMaximaVeiculos = 210,
                            Cidade = "Porto Alegre",
                            Email = "contato@autocenterxyz.com",
                            Endereco = "Rua dos Motores, 567",
                            Estado = "Rio Grande do Sul",
                            Nome = "Auto Center XYZ",
                            Telefone = "(51) 9876-2345"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CEP = "88000789",
                            CapacidadeMaximaVeiculos = 200,
                            Cidade = "Florianópolis",
                            Email = "vendas@carrosrapidos.com",
                            Endereco = "Av. das Acelerações, 789",
                            Estado = "Santa Catarina",
                            Nome = "Carros Rápidos",
                            Telefone = "(48) 9876-5678"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CEP = "50000123",
                            CapacidadeMaximaVeiculos = 230,
                            Cidade = "Recife",
                            Email = "contato@autocenterabcd.com",
                            Endereco = "Rua dos Motores, 123",
                            Estado = "Pernambuco",
                            Nome = "Auto Center ABCD",
                            Telefone = "(81) 5555-6789"
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FabricanteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Fabricantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFundacao = 1950,
                            Ativo = true,
                            Nome = "HyperCars",
                            PaisOrigem = "Brasil",
                            Website = "https://fabricantea.com"
                        },
                        new
                        {
                            Id = 2,
                            AnoFundacao = 1925,
                            Ativo = true,
                            Nome = "EcoMotors",
                            PaisOrigem = "Estados Unidos",
                            Website = "https://fabricanteb.com"
                        },
                        new
                        {
                            Id = 3,
                            AnoFundacao = 1960,
                            Ativo = true,
                            Nome = "SuperCarros",
                            PaisOrigem = "Itália",
                            Website = "https://www.supercarros.com"
                        },
                        new
                        {
                            Id = 4,
                            AnoFundacao = 1985,
                            Ativo = true,
                            Nome = "TechMotors",
                            PaisOrigem = "Japão",
                            Website = "https://www.techmotors.co.jp"
                        },
                        new
                        {
                            Id = 5,
                            AnoFundacao = 2003,
                            Ativo = true,
                            Nome = "TurboDrive",
                            PaisOrigem = "Coreia do Sul",
                            Website = "https://www.turbodrive"
                        },
                        new
                        {
                            Id = 6,
                            AnoFundacao = 2006,
                            Ativo = true,
                            Nome = "Electric Wheels",
                            PaisOrigem = "Holanda",
                            Website = "https://www.wlectricwheels.co.ho"
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.TipoVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoVeiculoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposVeiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Tipo = "Carro"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Tipo = "Moto"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Tipo = "Caminhão"
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VeiculoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("Modelo");

                    b.HasIndex("TipoVeiculoId");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoFabricacao = 2022,
                            Ativo = true,
                            Descricao = "Veículo confortável e econômico.",
                            FabricanteId = 1,
                            Modelo = "Sedan",
                            Preco = 55000.00m,
                            TipoVeiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnoFabricacao = 2021,
                            Ativo = true,
                            Descricao = "Moto ágil e potente.",
                            FabricanteId = 2,
                            Modelo = "Esportiva",
                            Preco = 12000.00m,
                            TipoVeiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            AnoFabricacao = 2022,
                            Ativo = true,
                            Descricao = "Um carro confortável e econômico.",
                            FabricanteId = 3,
                            Modelo = "Sedan",
                            Preco = 45000.00m,
                            TipoVeiculoId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnoFabricacao = 2023,
                            Ativo = true,
                            Descricao = "Um SUV espaçoso e versátil.",
                            FabricanteId = 3,
                            Modelo = "SUV",
                            Preco = 55000.00m,
                            TipoVeiculoId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnoFabricacao = 2024,
                            Ativo = true,
                            Descricao = "Um carro compacto e ágil.",
                            FabricanteId = 4,
                            Modelo = "Hatchback",
                            Preco = 35000.00m,
                            TipoVeiculoId = 1
                        },
                        new
                        {
                            Id = 6,
                            AnoFabricacao = 2023,
                            Ativo = true,
                            Descricao = "Uma caminhonete robusta e versátil.",
                            FabricanteId = 5,
                            Modelo = "Caminhonete",
                            Preco = 65000.00m,
                            TipoVeiculoId = 3
                        },
                        new
                        {
                            Id = 7,
                            AnoFabricacao = 2024,
                            Ativo = true,
                            Descricao = "Um carro compacto e ágil.",
                            FabricanteId = 5,
                            Modelo = "Hatchback",
                            Preco = 35000.00m,
                            TipoVeiculoId = 1
                        },
                        new
                        {
                            Id = 8,
                            AnoFabricacao = 2023,
                            Ativo = true,
                            Descricao = "Uma caminhonete robusta e versátil.",
                            FabricanteId = 6,
                            Modelo = "Caminhonete",
                            Preco = 65000.00m,
                            TipoVeiculoId = 3
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VendaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ConcessionariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProtocoloVenda")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConcessionariaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ClienteId = 1,
                            ConcessionariaId = 1,
                            DataVenda = new DateTime(2024, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 50000.00m,
                            ProtocoloVenda = "D236EAD2-E1C1-459C-B",
                            VeiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ClienteId = 2,
                            ConcessionariaId = 1,
                            DataVenda = new DateTime(2024, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 45000.00m,
                            ProtocoloVenda = "328A44F3-E584-4770-9",
                            VeiculoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ClienteId = 3,
                            ConcessionariaId = 2,
                            DataVenda = new DateTime(2024, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 55000.00m,
                            ProtocoloVenda = "636C89F6-9BE2-41BF-8",
                            VeiculoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ClienteId = 4,
                            ConcessionariaId = 2,
                            DataVenda = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 48000.00m,
                            ProtocoloVenda = "DA592B58-40E6-4095-8",
                            VeiculoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ClienteId = 5,
                            ConcessionariaId = 5,
                            DataVenda = new DateTime(2024, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 52000.00m,
                            ProtocoloVenda = "F99A1C88-3AFF-477C-8",
                            VeiculoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ClienteId = 6,
                            ConcessionariaId = 5,
                            DataVenda = new DateTime(2024, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 47000.00m,
                            ProtocoloVenda = "A79FC038-8E86-45CC-8",
                            VeiculoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ClienteId = 7,
                            ConcessionariaId = 7,
                            DataVenda = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 53000.00m,
                            ProtocoloVenda = "F046B055-A56E-4D5C-B",
                            VeiculoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            ClienteId = 8,
                            ConcessionariaId = 8,
                            DataVenda = new DateTime(2024, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 48000.00m,
                            ProtocoloVenda = "467E30E2-8BB3-43C9-B",
                            VeiculoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            ClienteId = 8,
                            ConcessionariaId = 8,
                            DataVenda = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 50000.00m,
                            ProtocoloVenda = "59233EC1-D5BC-4547-A",
                            VeiculoId = 8
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            ClienteId = 7,
                            ConcessionariaId = 7,
                            DataVenda = new DateTime(2024, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 45000.00m,
                            ProtocoloVenda = "891363E7-FCC8-4540-8",
                            VeiculoId = 7
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            ClienteId = 16,
                            ConcessionariaId = 6,
                            DataVenda = new DateTime(2024, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 55000.00m,
                            ProtocoloVenda = "FE5FCA9D-F89C-4B0D-8",
                            VeiculoId = 6
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            ClienteId = 15,
                            ConcessionariaId = 5,
                            DataVenda = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 48000.00m,
                            ProtocoloVenda = "3BB585D9-DEBD-468A-9",
                            VeiculoId = 5
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            ClienteId = 14,
                            ConcessionariaId = 7,
                            DataVenda = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 52000.00m,
                            ProtocoloVenda = "25BBE750-6C7B-4FA8-9",
                            VeiculoId = 4
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            ClienteId = 13,
                            ConcessionariaId = 5,
                            DataVenda = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 47000.00m,
                            ProtocoloVenda = "6196D799-57CA-4EEA-B",
                            VeiculoId = 3
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            ClienteId = 9,
                            ConcessionariaId = 3,
                            DataVenda = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PrecoVenda = 53000.00m,
                            ProtocoloVenda = "501C4B9A-15C5-4F0B-9",
                            VeiculoId = 2
                        });
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Veiculo", b =>
                {
                    b.HasOne("Concs.Dominio.Entidades.Fabricante", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concs.Dominio.Entidades.TipoVeiculo", "TipoVeiculo")
                        .WithMany()
                        .HasForeignKey("TipoVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");

                    b.Navigation("TipoVeiculo");
                });

            modelBuilder.Entity("Concs.Dominio.Entidades.Venda", b =>
                {
                    b.HasOne("Concs.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concs.Dominio.Entidades.Concessionaria", "Concessionaria")
                        .WithMany()
                        .HasForeignKey("ConcessionariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concs.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Concessionaria");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
